#!/usr/bin/env python3
"""Generate UPSTREAM_LEGENDS_OPCODE_MATRIX.md — ours vs upstream ShowEQ-Legends.

Upstream is an independent derivation, not an authority, so the point of this
table is to make every disagreement visible and to flag the rows upstream has
NOT re-derived for the active patch.

That last part is the one this rotation was built for: upstream ships partial
rotations and leaves the rest at their previous ids, so a current-looking file
carries dead mappings. Rows whose upstream `updated` predates the active patch
date are marked STALE-UP and must not be ported.

Usage:
  python3 tools/upstream_matrix.py \\
      conf/eql/opcodes.toml <up_zone.xml> <up_world.xml> \\
      --ref 6cd5907 --patch 08/04/26 [--stats <opcodestats.txt>] \\
      > ../UPSTREAM_LEGENDS_OPCODE_MATRIX.md

Get the upstream XML with (no merge needed — unrelated histories are fine):
  git -C showeq show <ref>:conf/zoneopcodes.xml
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
import xml.etree.ElementTree as ET
from pathlib import Path

# We de-suffix upstream's EQL-tagged names; keyed lookups miss without this.
ALIAS = {
    "OP_SelfPosEQL": "OP_SelfPos",
    "OP_DeathEQL": "OP_CombatRecord",
    "OP_LootMessageEQL": "OP_LootMessage",
    # Upstream renamed LootMessageEQL -> LiteralMessageEQL (their 9c4270d);
    # our row keeps the older neutral name, so both spellings alias onto it.
    "OP_LiteralMessageEQL": "OP_LootMessage",
    "OP_MoneyUpdateEQL": "OP_MoneyUpdate",
    "OP_LoadoutSwapEQL": "OP_LoadoutSwap",
    "OP_DzSwitchInfoEQL": "OP_DzSwitchInfo",
}

DIR_ABBR = {"server": "s", "client": "c", "both": "b"}


def load_ours(path: Path) -> dict:
    doc = tomllib.load(path.open("rb"))
    out = {}
    for stream in ("zone", "world"):
        for e in doc.get(stream, []):
            out[e["name"]] = {
                "stream": stream,
                "id": e.get("id", "ffff"),
                "priority": e.get("priority"),
                "updated": e.get("updated", ""),
                "payloads": "; ".join(
                    f"{DIR_ABBR.get(p.get('dir','both'),'?')}:"
                    f"{p.get('typename','uint8_t')}/{p.get('sizechecktype','none')}"
                    for p in e.get("payloads", [])
                ) or "-",
            }
    return out


def load_upstream(path: Path, stream: str) -> dict:
    text = path.read_text().replace(
        '<!DOCTYPE seqopcodes SYSTEM "seqopcodes.dtd">', "")
    out = {}
    for op in ET.fromstring(text).findall("opcode"):
        name = ALIAS.get(op.get("name", ""), op.get("name", ""))
        # De-suffixing collides an EQL row with the stock row of the same
        # neutral name (OP_MoneyUpdateEQL 48f9 vs OP_MoneyUpdate ffff, which
        # sits LATER in the file). Last-write-wins silently reported the live
        # mapping as unmapped, so a real id keeps its slot against a dead one.
        prev = out.get(name)
        if prev and prev["id"] != "ffff" and op.get("id", "ffff") == "ffff":
            continue
        out[name] = {
            "stream": stream,
            "id": op.get("id", "ffff"),
            "updated": op.get("updated", ""),
            "payloads": "; ".join(
                f"{DIR_ABBR.get(p.get('dir','both'),'?')}:"
                f"{p.get('typename','uint8_t')}/{p.get('sizechecktype','none')}"
                for p in op.findall("payload")
            ) or "-",
            "upname": op.get("name", ""),
        }
    return out


def load_fires(path: Path | None) -> dict:
    """opcode id -> fire count, from an --opcode-stats report."""
    if not path:
        return {}
    fires = {}
    for line in path.read_text().splitlines():
        m = re.match(r"^0x([0-9a-f]{4})\s+\S+\s+(\d+)\s", line)
        if m:
            fires[m.group(1)] = int(m.group(2))
    return fires


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("ours")
    ap.add_argument("up_zone")
    ap.add_argument("up_world")
    ap.add_argument("--ref", required=True, help="upstream commit/tag the XML came from")
    ap.add_argument("--patch", required=True, help="active patch date as upstream writes it, e.g. 08/04/26")
    ap.add_argument("--stats", help="an --opcode-stats report for the fires column")
    a = ap.parse_args(argv[1:])

    ours = load_ours(Path(a.ours))
    up = load_upstream(Path(a.up_zone), "zone")
    up.update(load_upstream(Path(a.up_world), "world"))
    fires = load_fires(Path(a.stats) if a.stats else None)

    print("# EQL opcode matrix — ours vs upstream ShowEQ-Legends")
    print()
    print("Generated by `scry-cpp/tools/upstream_matrix.py`. Regenerate after")
    print("any sync; do not edit by hand.")
    print()
    print(f"Sources: our `scry-cpp/conf/eql/opcodes.toml`; upstream @`{a.ref}`")
    print("(`conf/{zone,world}opcodes.xml`). `fires` = occurrences in the capture")
    print("passed as `--stats`; blank = did not fire, which for most opcodes just")
    print("means the event never happened in the recording.")
    print()
    print(f"**`up upd` is load-bearing.** Upstream ships PARTIAL rotations. Any row")
    print(f"whose upstream date is not `{a.patch}` was not re-derived for the active")
    print("patch, so its id is almost certainly dead — those are flagged `STALE-UP`")
    print("and must not be ported. Rows where we deliberately hunted our own id")
    print("against a current capture show `OURS`.")
    print()
    print("`gate`: `match` = size must equal the struct exactly; `none` = **no size")
    print("check, so a mis-mapped `none` opcode fails silently with no warning**;")
    print("`modulus` = array stride.")
    print()
    print("Where upstream suffixes a name `EQL` and we use the neutral name, the rows")
    print("are paired under OUR name — **we do not use an EQL suffix.**")
    print()
    print("| opcode | stream | pri | our id | our payload dir:struct/gate | our upd "
          "| up id | up payload | up upd | fires | verdict |")
    print("|---|---|---|---|---|---|---|---|---|---|---|")

    stale = agree = differ = ours_only = 0
    for name in sorted(set(ours) | set(up)):
        o = ours.get(name)
        u = up.get(name)
        oid = o["id"] if o else "-"
        uid = u["id"] if u else "-"
        uupd = u["updated"] if u else "-"
        f = fires.get(oid, "") if oid != "ffff" else ""

        up_current = bool(u) and uupd == a.patch
        up_stale = bool(u) and uid != "ffff" and not up_current

        if o and oid != "ffff" and up_stale:
            # We hunted a current id where upstream's is dead. Say that, rather
            # than only flagging their staleness — it's the actionable half.
            verdict = "**OURS** (up stale)"
            ours_only += 1
        elif up_stale:
            verdict = "**STALE-UP**"
            stale += 1
        elif o and u and oid == uid and oid != "ffff":
            verdict = "same id"
            agree += 1
        elif o and oid != "ffff" and (not u or uid == "ffff"):
            verdict = "**OURS**"
            ours_only += 1
        elif o and u and oid != uid and "ffff" not in (oid, uid):
            verdict = "**DIFFERS**"
            differ += 1
        else:
            verdict = ""

        pri = "" if not o or o.get("priority") is None else str(o["priority"])
        upname = f" [{u['upname']}]" if u and u["upname"] != name else ""
        print(f"| {name}{upname} | {(o or u)['stream']} | {pri} | `{oid}` | "
              f"{o['payloads'] if o else '-'} | {o['updated'] if o else '-'} | "
              f"`{uid}` | {u['payloads'] if u else '-'} | {uupd} | {f} | {verdict} |")

    print()
    print(f"**Totals:** {agree} same id, {differ} differ, {ours_only} ours-only "
          f"(hunted), {stale} stale upstream rows not ported.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
